<?php
/*
 * SOZO Design Ltd
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 *  that is bundled with this package in the file LICENSE.
 *  It is also available through the world-wide-web at this URL:
 *  http://opensource.org/licenses/osl-3.0.php
 *
 * @category    SOZO Design Ltd
 * @package     Sozo_OutdatedBrowserWarning
 * @copyright   Copyright (c) SOZO Design Ltd (https://sozodesign.co.uk)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Sozo\OutdatedBrowserWarning\Block\Frontend $block */
if ($block->displayBrowserNotSupportedNotice()) :
    ?>
<div style="display: none;" class="message global browserwarning" id="browser-warning" data-mage-init='{"sozoOutdatedBrowserWarning":{}}'>
    <p>
        <?= $block->escapeHtml(__('You are using an <strong>outdated</strong> browser. Please <a href="%1" target="_blank" rel="external">upgrade your browser</a> to improve your experience', 'https://browsehappy.com/'), ['a','strong']) ?>
    </p>
</div>
    <?php
endif;
